/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assgui;

/**
 *
 * @author Arnav Shindolkar
 */
public class OfficeMenu extends javax.swing.JFrame {

    /**
     * Creates new form OfficeMenu
     */
    public OfficeMenu() {
        initComponents();
    }

    RemoveEstate rm_estate_page = new RemoveEstate();
    RemoveAgent rm_agent_page = new RemoveAgent();
    Show_all_estates show_estates_page = new Show_all_estates();
    Show_all_agents show_agents_page = new Show_all_agents();
    AddAgent add_agent_page = new AddAgent();
    AddEstate add_estate_page = new AddEstate();
    UpdateAgent update_agent_page = new UpdateAgent();
    UpdateEstate update_estate_page = new UpdateEstate();
    Customers customers_page = new Customers();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        show_agents = new javax.swing.JButton();
        add_agent = new javax.swing.JButton();
        remove_agent = new javax.swing.JButton();
        show_all_estates = new javax.swing.JButton();
        add_estate = new javax.swing.JButton();
        update_estate = new javax.swing.JButton();
        remove_estate = new javax.swing.JButton();
        update_agent = new javax.swing.JButton();
        show_customers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Office Menu");

        show_agents.setText("Show All the Agents");
        show_agents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_agentsActionPerformed(evt);
            }
        });

        add_agent.setText("Add An Agent");
        add_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_agentActionPerformed(evt);
            }
        });

        remove_agent.setText("Remove An Agent");
        remove_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_agentActionPerformed(evt);
            }
        });

        show_all_estates.setText("Show All the Estates");
        show_all_estates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_all_estatesActionPerformed(evt);
            }
        });

        add_estate.setText("Add An Estate");
        add_estate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_estateActionPerformed(evt);
            }
        });

        update_estate.setText("Update An Estate");
        update_estate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_estateActionPerformed(evt);
            }
        });

        remove_estate.setText("Remove an Estate");
        remove_estate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_estateActionPerformed(evt);
            }
        });

        update_agent.setText("Update An Agent");
        update_agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_agentActionPerformed(evt);
            }
        });

        show_customers.setText("Show All Customers");
        show_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_customersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(show_agents, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(add_agent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(remove_agent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update_agent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(show_all_estates, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(add_estate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update_estate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(remove_estate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 86, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(show_customers, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(show_all_estates, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(show_agents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_estate, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(add_agent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(update_estate, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(update_agent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remove_estate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove_agent, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(show_customers, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void show_agentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_agentsActionPerformed
        // TODO add your handling code here:
        show_agents_page.setVisible(true);
        show_agents_page.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_show_agentsActionPerformed

    private void show_all_estatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_all_estatesActionPerformed
        // TODO add your handling code here:
        show_estates_page.setVisible(true);
        show_estates_page.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_show_all_estatesActionPerformed

    private void remove_estateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_estateActionPerformed
        // TODO add your handling code here:
        rm_estate_page.setVisible(true);
        rm_estate_page.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_remove_estateActionPerformed

    private void update_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_agentActionPerformed
        // TODO add your handling code here:
        update_agent_page.setVisible(true);
        update_agent_page.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_update_agentActionPerformed

    private void remove_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_agentActionPerformed
        // TODO add your handling code here:
        rm_agent_page.setVisible(true);
        rm_agent_page.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_remove_agentActionPerformed

    private void add_agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_agentActionPerformed
        // TODO add your handling code here:
        add_agent_page.setVisible(true);
        add_agent_page.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_add_agentActionPerformed

    private void add_estateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_estateActionPerformed
        // TODO add your handling code here:
        add_estate_page.setVisible(true);
        add_estate_page.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_add_estateActionPerformed

    private void update_estateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_estateActionPerformed
        // TODO add your handling code here:
        update_estate_page.setVisible(true);
        update_estate_page.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_update_estateActionPerformed

    private void show_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_customersActionPerformed
        // TODO add your handling code here:
        customers_page.setVisible(true);
        customers_page.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_show_customersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfficeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_agent;
    private javax.swing.JButton add_estate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton remove_agent;
    private javax.swing.JButton remove_estate;
    private javax.swing.JButton show_agents;
    private javax.swing.JButton show_all_estates;
    private javax.swing.JButton show_customers;
    private javax.swing.JButton update_agent;
    private javax.swing.JButton update_estate;
    // End of variables declaration//GEN-END:variables
}
